### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by MrDmitry1107** [LimerBoy/MagmaOsint#1]
![15809753357928727917793492187547](https://user-images.githubusercontent.com/54665743/73916322-4b2e2680-48ce-11ea-9650-49980b854e2c.jpg)
Что делать?

**Comment by LimerBoy** [comment]
Пробуй python3

**Comment by MrDmitry1107** [comment]
Pyrhon3 вообще не работает

**Comment by LimerBoy** [comment]
Пробуй на винде запускать

**Comment by LimerBoy** [comment]
У меня работает
![](https://i.ibb.co/YtYKswk/Screenshot-20200207-092605-Termux.png)
